name: Token Refresh

on:
  workflow_dispatch:  
jobs:
  refresh_token:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run getToken script
        run: node api/getToken.js

      - name: Commit and push updated access token
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add api/access_token.json
          git commit -m "Update access token"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/zelinho/Robit.git
        env:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
